<?php
/**
 * Minicode - only need to need!
 *
 * An open source hyper-light web application agile development framework
 *
 * @package       Minicode
 * @author        Wanglong
 * @copyright     Copyright (c) 2012 - 2013, Minicode.
 * @license       http://minicode.org/docs/license
 * @link          http://minicode.org
 */

/**
 *--------------------------------------------------------------------------
 * URI PROTOCOL
 *--------------------------------------------------------------------------
 *
 * This item determines which server global should be used to retrieve the
 * URI string.  The default setting of 'AUTO' works for most servers.
 * If your links do not seem to work, try one of the other delicious flavors:
 *
 * 'AUTO'			Default - auto detects
 * 'PATH_INFO'		Uses the PATH_INFO
 * 'QUERY_STRING'	Uses the QUERY_STRING
 * 'REQUEST_URI'	Uses the REQUEST_URI
 * 'ORIG_PATH_INFO'	Uses the ORIG_PATH_INFO
 */

$config['uri_protocol']	= 'AUTO';

/**
 *--------------------------------------------------------------------------
 * Enable Query Strings
 *--------------------------------------------------------------------------
 *
 * By default Minicode uses search-engine friendly segment based URLs:
 * example.com/who/what/where/
 *
 * You can optionally enable standard query string based URLs:
 * example.com?who=me&what=something&where=here
 *
 * Must be setting: $config['uri_protocol'] = 'QUERY_STRING';
 */

$config['controller_trigger']   = 'c';
$config['function_trigger']     = 'm';
$config['directory_trigger']    = 'd'; // experimental not currently in use

/**
 *--------------------------------------------------------------------------
 * URL suffix
 *--------------------------------------------------------------------------
 *
 * This option allows you to add a suffix to all URLs generated by Minicode.
 */

$config['url_suffix'] = '';

/**
 *--------------------------------------------------------------------------
 * Allowed URL Characters
 *--------------------------------------------------------------------------
 *
 * This lets you specify with a regular expression which characters are permitted
 * within your URLs.  When someone tries to submit a URL with disallowed
 * characters they will get a warning message.
 *
 * As a security measure you are STRONGLY encouraged to restrict URLs to
 * as few characters as possible.  By default only these are allowed: a-z 0-9~%.:_-
 *
 * Leave blank to allow all characters -- but only if you are insane.
 *
 * DO NOT CHANGE THIS UNLESS YOU FULLY UNDERSTAND THE REPERCUSSIONS!!
 */

$config['permitted_uri_chars'] = 'a-z 0-9~%.:_\-';

/**
 *--------------------------------------------------------------------------
 * Session Variables
 *--------------------------------------------------------------------------
 *
 * 'sess_expiration'      = the number of SECONDS you want the session to last.
 *   by default sessions last 7200 seconds (two hours).  Set to zero for no expiration.
 * 'sess_expire_on_close' = Whether to cause the session to expire automatically
 *   when the browser window is closed
 * 'sess_use_database'    = Whether to save the session data to a database
 * 'sess_table_name'      = The name of the session database table
 * 'sess_match_ip'        = Whether to match the user's IP address when reading the session data
 * 'sess_match_useragent' = Whether to match the User Agent when reading the session data
 * 'sess_time_to_update'  = how many seconds between CI refreshing Session Information
 */

$config['sess_expiration']		= 7200;
$config['sess_expire_on_close']	= FALSE;
$config['sess_use_database']	= FALSE;
$config['sess_table_name']		= 'mc_sessions';
$config['sess_match_ip']		= FALSE;
$config['sess_match_useragent']	= TRUE;
$config['sess_time_to_update']	= 300;

/**
 *--------------------------------------------------------------------------
 * Cookie Related Variables
 *--------------------------------------------------------------------------
 *
 * 'cookie_prefix' = Set a prefix if you need to avoid collisions
 * 'cookie_domain' = Set to .your-domain.com for site-wide cookies
 * 'cookie_path'   =  Typically will be a forward slash
 * 'cookie_secure' =  Cookies will only be set if a secure HTTPS connection exists.
 */

$config['cookie_prefix']	= "";
$config['cookie_domain']	= "";
$config['cookie_path']		= "/";
$config['cookie_secure']	= FALSE;

// End of file config.php
// By Minicode