<?php
/**
 * Minicode - only need to need!
 *
 * An open source hyper-light web application agile development framework
 *
 * @package       Minicode
 * @author        Wanglong
 * @copyright     Copyright (c) 2012 - 2013, Minicode.
 * @license       http://minicode.org/docs/license
 * @link          http://minicode.org
 */

/**
 *--------------------------------------------------------------------------
 * URI PROTOCOL
 *--------------------------------------------------------------------------
 *
 * This item determines which server global should be used to retrieve the
 * URI string.  The default setting of 'AUTO' works for most servers.
 * If your links do not seem to work, try one of the other delicious flavors:
 *
 * 'AUTO'           Default - auto detects
 * 'PATH_INFO'      Uses the PATH_INFO
 * 'QUERY_STRING'   Uses the QUERY_STRING
 * 'REQUEST_URI'    Uses the REQUEST_URI
 * 'ORIG_PATH_INFO' Uses the ORIG_PATH_INFO
 */

$config['uri_protocol']	= 'AUTO';

/**
 *--------------------------------------------------------------------------
 * Enable Query Strings
 *--------------------------------------------------------------------------
 *
 * By default Minicode uses search-engine friendly segment based URLs:
 * example.com/who/what/where/
 *
 * You can optionally enable standard query string based URLs:
 * example.com?who=me&what=something&where=here
 *
 * Must be setting: $config['uri_protocol'] = 'QUERY_STRING';
 */

$config['controller_trigger']   = 'c';
$config['function_trigger']     = 'm';
$config['directory_trigger']    = 'd'; // experimental not currently in use

/**
 *--------------------------------------------------------------------------
 * URL suffix
 *--------------------------------------------------------------------------
 *
 * This option allows you to add a suffix to all URLs generated by Minicode.
 */

$config['url_suffix'] = '';

/**
 *--------------------------------------------------------------------------
 * Allowed URL Characters
 *--------------------------------------------------------------------------
 *
 * This lets you specify with a regular expression which characters are permitted
 * within your URLs.  When someone tries to submit a URL with disallowed
 * characters they will get a warning message.
 *
 * As a security measure you are STRONGLY encouraged to restrict URLs to
 * as few characters as possible.  By default only these are allowed: a-z 0-9~%.:_-
 *
 * Leave blank to allow all characters -- but only if you are insane.
 *
 * DO NOT CHANGE THIS UNLESS YOU FULLY UNDERSTAND THE REPERCUSSIONS!!
 */

$config['permitted_uri_chars'] = 'a-z 0-9~%.:_\-';

/**
 *--------------------------------------------------------------------------
 * Automatic loading paths extensions
 *--------------------------------------------------------------------------
 *
 * Based on the original loading paths extensions, Do not suggest there 
 * are too many extension path, this will affect retrieval performance.
 * Note: They are all relative to the project application directory.
 */

$config['autoload_paths_ext'] = array('bases');

// End of file config.php
// By Minicode